# Generated by Django 4.2.30 on 2026-06-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi-robot', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_offerings/')),
                ('features', models.JSONField(default=list)),
                ('highlight', models.CharField(blank=True, help_text='Short badge text, e.g. "Most Popular"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Offering',
                'verbose_name_plural': 'Service Offerings',
                'ordering': ['order', 'title'],
            },
        ),
    ]
