# Generated by Django 4.2.30 on 2026-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.service',),
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
            ],
            options={
                'verbose_name': 'Service Offering',
                'verbose_name_plural': 'Service Offerings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.service',),
        ),
        migrations.AddField(
            model_name='service',
            name='record_type',
            field=models.CharField(choices=[('service', 'Service Offering'), ('portfolio', 'Portfolio Project')], default='service', help_text='Service Offering = what we provide. Portfolio Project = past client work.', max_length=20),
        ),
    ]
